  services:

    # Serviço de Banco de Dados PostgreSQL
    db:
      container_name: ${DB_CONTAINER}
      image: postgres:16-bullseye
      environment:
        POSTGRES_PASSWORD: ${PGADMIN_PASSWORD}
        POSTGRES_DB: ${PG_DATABASE}
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      ports:
        - "${PG_PORT}:${PG_PORT}"

    # Serviço pgAdmin para gerenciar o PostgreSQL
    pgadmin:
      container_name: pgadmin_container
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      ports:
        - "8080:80"
      depends_on:
        - db

    # Serviço para a aplicação Python "API Previsoes"
    backend:
      container_name: back_container
      build:
        context: ./backend
        dockerfile: dockerfile.backend
      environment:
        DATABASE_URL: ${DATABASE_URL}
      ports:
        - ${BACKEND_PORT}:${BACKEND_PORT}
      depends_on:
        - db

    # Serviço para a aplicação Node.js "gerenciador-estoque"
    frontend:
      container_name: front_container
      build:
        context: ./Frontend
        dockerfile: dockerfile.frontend
      environment:
        PG_USER: ${PG_USER}
        PG_HOST: ${DB_CONTAINER}
        PG_DATABASE: ${PG_DATABASE}
        PG_PASSWORD: ${PG_PASSWORD}
        PG_PORT: ${PG_PORT}
        NEXT_PUBLIC_PY_BACKEND: ${NEXT_PUBLIC_PY_BACKEND}
      ports:
        - ${FRONTEND_PORT}:${FRONTEND_PORT}
      depends_on:
        - db
        - backend